<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="four_wheel_robot_laser">

    <!-- 激光雷达属性 Lidar Properties -->
    <xacro:property name="lidar_radius" value="0.05" />
    <xacro:property name="lidar_height" value="0.08" />
    <xacro:property name="lidar_mass" value="0.5" />
    <xacro:property name="chassis_height" value="0.1" />
    
    <!-- 激光雷达材料 Lidar Material -->
    <material name="lidar_material">
        <color rgba="0.8 0.2 0.2 1.0"/>
    </material>

    <!-- 激光雷达宏定义 Lidar Macro -->
    <xacro:macro name="lidar_sensor" params="parent">
        <link name="lidar_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
                </geometry>
                <material name="lidar_material"/>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="${lidar_mass}"/>
                <inertia ixx="${lidar_mass*(3*lidar_radius*lidar_radius+lidar_height*lidar_height)/12}" ixy="0" ixz="0"
                         iyy="${lidar_mass*(3*lidar_radius*lidar_radius+lidar_height*lidar_height)/12}" iyz="0"
                         izz="${lidar_mass*lidar_radius*lidar_radius/2}"/>
            </inertial>
        </link>

        <!-- 激光雷达关节 Lidar Joint - 位于车子中央上方 -->
        <joint name="lidar_joint" type="fixed">
            <parent link="${parent}"/>
            <child link="lidar_link"/>
            <!-- 修正：相对于base_link中心，向上偏移半个chassis高度和半个lidar高度 -->
            <origin xyz="0 0 ${chassis_height/2 + lidar_height/2 + 0.01}" rpy="0 0 0"/>
        </joint>

        <!-- Gazebo 激光雷达插件 -->
        <gazebo reference="lidar_link">
            <sensor type="ray" name="lidar_sensor">
                <pose>0 0 0 0 0 0</pose>
                <visualize>true</visualize>
                <update_rate>40</update_rate>
                <ray>
                    <scan>
                        <horizontal>
                            <samples>720</samples>
                            <resolution>1</resolution>
                            <min_angle>-3.14159</min_angle>
                            <max_angle>3.14159</max_angle>
                        </horizontal>
                    </scan>
                    <range>
                        <min>0.12</min>
                        <max>30.0</max>
                        <resolution>0.015</resolution>
                    </range>
                    <noise>
                        <type>gaussian</type>
                        <mean>0.0</mean>
                        <stddev>0.01</stddev>
                    </noise>
                </ray>
                <plugin name="gazebo_ros_lidar_controller" filename="libgazebo_ros_ray_sensor.so">
                    <ros>
                        <namespace>/robot</namespace>
                        <argument>~/out:=scan</argument>
                    </ros>
                    <output_type>sensor_msgs/LaserScan</output_type>
                    <frame_name>lidar_link</frame_name>
                </plugin>
            </sensor>
        </gazebo>
    </xacro:macro>

</robot>